# -*- coding: utf-8 -*-
"""RAGbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TfSyQv0L37U-ndCl1t8TmE7eRl6ZCZHT
"""

!pip -q install langchain langchain-community langchain-openai
!pip -q install faiss-cpu rank-bm25 tiktoken
!pip -q install wikipedia arxiv pymupdf
!pip -q install gradio

import os
import numpy as np

from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_community.document_loaders import WikipediaLoader, ArxivLoader
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_community.vectorstores import FAISS

from rank_bm25 import BM25Okapi

import os
from google.colab import userdata
secret_key = userdata.get('OPENAI_API_KEY')
os.environ["OPENAI_API_KEY"] = secret_key

print("API Key loaded securely! 🔒")

TOPIC = "Internet of Things"

wiki_docs = WikipediaLoader(query=TOPIC, load_max_docs=5).load()

arxiv_docs = ArxivLoader(
    query=TOPIC,
    load_max_docs=5,
    load_all_available_meta=True
).load()

documents = wiki_docs + arxiv_docs

print("Total documents loaded:", len(documents))

splitter = RecursiveCharacterTextSplitter(
    chunk_size=900,
    chunk_overlap=200
)

chunks = splitter.split_documents(documents)
print("Total chunks:", len(chunks))

embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

vector_db = FAISS.from_documents(chunks, embeddings)

corpus = [doc.page_content for doc in chunks]
tokenized_corpus = [doc.split(" ") for doc in corpus]

bm25 = BM25Okapi(tokenized_corpus)

def hybrid_search(query, k=4):

    # Dense semantic search
    dense_docs = vector_db.similarity_search(query, k=k)

    # Sparse keyword search
    tokenized_query = query.split(" ")
    scores = bm25.get_scores(tokenized_query)
    top_idx = np.argsort(scores)[::-1][:k]
    sparse_docs = [chunks[i] for i in top_idx]

    # Merge + remove duplicates
    combined = dense_docs + sparse_docs
    unique_docs = list({doc.page_content: doc for doc in combined}.values())

    return unique_docs

llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0
)

def ask_rag(question):

    docs = hybrid_search(question)

    context = "\n\n".join([d.page_content for d in docs])

    prompt = f"""
You are a research assistant AI.
Answer ONLY using the provided context.
If answer is missing say: Not present in knowledge base.

Context:
{context}

Question:
{question}
"""

    response = llm.invoke(prompt)
    return response.content

#UI BLOCK
import gradio as gr

def chat(message, history):
    reply = ask_rag(message)
    history.append((message, reply))
    return "", history


css = """
/* Page */
body { background:#f1f3f4; }

/* Remove avatar + copy button + decorations */
.message img { display:none !important; }
.message button { display:none !important; }
.avatar { display:none !important; }
.copy-button { display:none !important; }
button[aria-label="Copy"] { display:none !important; }

/* Chat container */
.chatbot {
    background:white !important;
    border-radius:18px !important;
    border:1px solid #e0e0e0 !important;
}

/* User bubble */
.message.user .bubble {
    background:#e3f2fd !important;
    border-radius:18px !important;
}

/* Bot bubble */
.message.bot .bubble {
    background:#f5f5f5 !important;
    border-radius:18px !important;
}

/* Input */
textarea {
    border-radius:25px !important;
    padding:14px !important;
    font-size:16px !important;
}

/* Hide footer */
footer {visibility:hidden}
"""

with gr.Blocks(css=css) as demo:

    gr.Markdown("## ✨ Research Assistant")
    gr.Markdown("Ask anything about your topic")

    chatbot = gr.Chatbot(height=520, render_markdown=True)

    with gr.Row():
        msg = gr.Textbox(placeholder="Ask anything...", show_label=False, scale=8)
        send = gr.Button("➤", scale=1)

    send.click(chat, [msg, chatbot], [msg, chatbot])
    msg.submit(chat, [msg, chatbot], [msg, chatbot])

demo.launch()